#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.jidi.standard.entity
  mapperLocations: classpath:mapper/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://rm-2ze40qt16dald65x9to.mysql.rds.aliyuncs.com:3306/standard
    username: myrtdv
    password: m8%swIl$3wfG(s
    driver-class-name: com.mysql.jdbc.Driver